@startuml

skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 1
title Authenticate over iFrame with login and password\nInvalid login/password

actor User
participant Site
participant "CentralAuth Server" as CAS
participant "CentralAuth API" as CAA
participant "BruteForce" as BF_MS <<MicroService>>
participant "User Info" as UI_MS <<MicroService>>
participant Logger as LOG_MS <<MicroService>>
participant Notification as NOTIF_MS <<MicroService>>
participant DataBase as DB
participant MessageBroker as Broker
participant NotificationWorker
participant LoggerWorker
participant "SMS Service" as SMS
participant "Email Service" as Email

User -> Site : Request authenticate
Site -> CAS : Init iFrame
CAS -> User : Show iFrame

User -> CAA : Submit login form

hnote over CAA: Check bruteforce cases\nSee **bruteforce_reaction**

CAA -> UI_MS : Check login and password
UI_MS -> DB : Get space/app settings
DB -> UI_MS
UI_MS -> DB : Get user crypt password by login
DB -> UI_MS
UI_MS -> CAA : Unsuccessful authentication
CAA -> BF_MS : Add unsuccessful attempt
CAA -> User : Show error message
BF_MS -> Broker : Send unsuccessful authentication event
Broker o--> NotificationWorker : Read event
NotificationWorker -> NOTIF_MS
NOTIF_MS -> DB : Get available transport
DB -> NOTIF_MS
NOTIF_MS --> SMS : Send SMS
NOTIF_MS --> Email : Send email
Broker o--> LoggerWorker : Read event
LoggerWorker -> LOG_MS : Save log
LOG_MS -> DB

@enduml