{{- if .Values.enableMongo }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo
type: Opaque
data:
  MONGO_SERVER: {{ printf "mongodb://%s-mongo:27017" .Release.Name | b64enc }}
  MONGO_DATABASE: {{ printf "p1auth" | b64enc }}
  MONGO_USER: {{ printf "root" | b64enc }}
  MONGO_PASSWORD: {{ printf "strongpassword#" | b64enc }}
---  
## PV is commented out to use dynamic nfs provisions in test env
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: {{ .Release.Name }}-mongo
#   labels:
#     app: {{ .Chart.Name }}
#     release: {{ .Release.Name }}
#     heritage: {{ .Release.Service }}
# spec:
#   persistentVolumeReclaimPolicy: Retain
#   capacity:
#     storage: 15Gi
#   accessModes:
#     - ReadWriteOnce
#   nfs:
#     server: 172.29.13.72
#     path: "/k8sdata/{{ .Release.Name }}-mongo"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-mongo
spec:
## selector and storage class are commented out to use dynamic nfs provisions in test env
#  storageClassName: ""
#  selector:
#    matchLabels:
#      app: {{ .Chart.Name }}
#      release: {{ .Release.Name }}
#      heritage: {{ .Release.Service }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: mongo
    spec:
      volumes:
      - name: {{ .Release.Name }}-mongo
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mongo
      containers:
      - name: mongo
        image: library/mongo:4.1.3
        {{- if .Values.prodRelease }}
        args: ["--auth"]
        {{- end }}}}
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: {{ .Release.Name }}-mongo
          mountPath: /data/db
          readOnly: false
{{- end }}